[package]
name = "orbital_services"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.1.0-alpha.5"
orbital_headers = { path = "../models/orbital_headers" }


[lib]
name = "orbital_services"
path = "mod.rs"