[package]
name = "orbital_cli_subcommand"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
clap = "2.33"
container_builder = { path = "../../../../lib/container_builder" }
config_parser = { path = "../../../../lib/config_parser" }
git_meta = { path = "../../../../lib/git_meta" }
tokio = "0.1"
orbital_headers = { path = "../../../../models/orbital_headers" }
orbital_services = { path = "../../../../services" }
tower-hyper = "0.1"
futures = "0.1"
log = "0.4"
tower-grpc = "0.1"
hyper = "0.12"
http = "0.1"
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-util = "0.1"

[lib]
name = "subcommand"
path = "mod.rs"