[package]
name = "orbital_cli_subcommand"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
clap = "2.33"
container_builder = { path = "../../../../lib/container_builder" }
config_parser = { path = "../../../../lib/config_parser" }
git_meta = { path = "../../../../lib/git_meta" }
orbital_headers = { path = "../../../../models/orbital_headers" }
orbital_services = { path = "../../../../services" }
log = "0.4"
tonic = "0.1.0-alpha.5"

[lib]
name = "subcommand"
path = "mod.rs"