[package]
name = "git_meta"
version = "0.1.0"
authors = ["T.J. Telan <tjtelan@level11.com>"]
edition = "2018"

[dependencies]
git2 = "0.10.1"
itertools = "0.8"
url = "2.1.0"

[lib]
name = "git_meta"
path = "mod.rs"